server:
  port: 10002
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://47.102.156.24:3306/aiops?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8
    username: root
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    port: 5672
    host: 123.56.7.250
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          # 重试的最大次数
          max-attempts: 3
          # 重试间隔最多10s
          max-interval: 10000
          #每次重试的因子是1.0 等差
          multiplier: 1.0
  mail:
    password: sgmaqbchqpyobhfi
    username: 245368045@qq.com
    from: 245368045@qq.com
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

aiops:
  env: dev
  name: aiops-notice