server:
  port: 10001
swagger:
  enable: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 2
    host: 47.102.156.24
    port: 6379
    pool:
    max-active: 20
  datasource:
    name: test
    url: jdbc:mysql://47.102.156.24:3306/aiops?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8
    username: root
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

aiops:
  env: dev
  name: aiops-user

