server:
  port: 10000
swagger:
  enable: true

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cache:
    type: redis
    redis:
      time-to-live: 20000
      cache-null-values: false
  redis:
    database: 2
    host: 47.102.156.24
    port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 0
  datasource:
    name: test
    url: jdbc:mysql://47.102.156.24:3306/aiops?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8
    username: root
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: 123.56.7.250
    port: 5672
    username: guest
    password: guest
    # sentinel:
    #   transport:
    #     dashboard: 172.31.178.50:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false