server:
  port: 10005
swagger:
  enable: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://123.56.7.250:3306/metis?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: metis@123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    port: 5672
    host: 123.56.7.250
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

aiops:
  env: dev
  name: aiops-detector
metis:
  start:
    bootrap: http://123.56.7.250:8080